development:
  adapter: postgresql
  encoding: utf8
  database: ccem_development
  pool: 5
  username: Kevin
  password: 247Kevin!88!

test:
  adapter: postgresql
  encoding: utf8
  database: ccem_test
  pool: 5
  username: Kevin
  password: ''

production:
  adapter: postgresql
  encoding: utf8
  database: rails_ccemachine
  username: rails_ccemachine_user
  password: 3D.X6JkNr)$mb]R
  host: 107.170.63.250
  port: 5432
  pool: 100