development:
  adapter: postgresql
  encoding: unicode
  database: ccem_development
  pool: 5
  username: Kevin
  password: 247Kevin!88!

test:
  adapter: postgresql
  encoding: unicode
  database: ccem_test
  pool: 5
  username: Kevin
  password: ''

production:
  adapter: postgresql
  encoding: unicode
  database: ccem_production
  pool: 5
  username: btcdeploy
  password: ovoOGvL7n3dRyU9ZzTey
