development:
  adapter: postgresql
  encoding: unicode
  database: btc-market-exchange_development
  pool: 5
  username: Kevin
  password: 247Kevin!88!

test:
  adapter: postgresql
  encoding: unicode
  database: btc-market-exchange_test
  pool: 5
  username: Kevin
  password: ''

production:
  adapter: postgresql
  encoding: unicode
  database: btc-market-exchange_production
  pool: 5
  username: btcdeploy
  password: ovoOGvL7n3dRyU9ZzTey
